name: Cypress Component Tests
on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress component tests
        id: cypress-tests
        run: |
          npx cypress run --component
        continue-on-error: true

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
            name: cypress-snapshots
            path: cypress/snapshots