name: Cypress Component Tests

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Veya projeniz için uygun Node.js sürümü

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # legacy-peer-deps eklenmiş

      - name: Run Cypress component tests
        id: cypress-tests
        run: |
          npx cypress run --component || true  # Hata durumunda işleme devam et

      - name: Capture screenshot on failure
        if: steps.cypress-tests.outcome == 'failure'  # Eğer testler başarısızsa
        run: |
          mkdir -p screenshots
          cp -r cypress/screenshots/* screenshots/  # Ekran görüntülerini al
          
      - name: Upload screenshots
        if: steps.cypress-tests.outcome == 'failure'  # Eğer testler başarısızsa
        uses: actions/upload-artifact@v3  # Güncel sürüm
        with:
          name: screenshots
          path: screenshots/
