name: Cypress Component Tests
on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress component tests
        id: cypress-tests
        run: |
          npx cypress run --component
        continue-on-error: true

      - name: Upload screenshots if tests fail
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-failure-screenshots
          path: |
            cypress/screenshots/**/*.png
          if-no-files-found: warn
          retention-days: 7

      - name: Print test failure details
        if: failure()
        run: |
          echo "Test Failure Details:"
          echo "Failed Test: Counter Component - decrements count"
          echo "Screenshot Location: cypress/screenshots/counter.cy.js/"
          ls -la cypress/screenshots/counter.cy.js/