name: Cypress Component Tests
on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest

    env:
        TERM: xterm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress component tests
        id: cypress-tests
        run: |
          npx cypress run --component
    

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

    