name: React Cypress Component Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Yerleşik npm önbelleğini etkinleştirir

    # Kök NPM bağımlılıklarını önbelleğe alma
    - name: Cache Root NPM dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-root-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-root-

    # Kök Bağımlılıklarını Kurma
    - name: Install Root dependencies
      run: |
        npm ci --legacy-peer-deps
      working-directory: .

    # Component Testlerini Çalıştırma
    - name: Run Component Tests
      run: npx cypress run --component
      working-directory: /Users/musti/AquaProjects/React-Cypress-Test/cypress/component
      env:
        CI: true

    # Test Sonuçlarını Yükleme
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: |
          cypress/videos
          cypress/screenshots
          cypress/reports
        retention-days: 30

    # Hata Durumunda Screenshot'ları Yükleme
    - name: Upload Failure Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        retention-days: 5
