name: React Cypress Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: cypress-react-app  # React uygulamanızın bulunduğu dizin

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: cypress-react-app/package-lock.json  # package-lock.json'ın yolu

    - name: Install dependencies
      run: |
        npm ci
        npx cypress verify

    # Build React uygulaması
    - name: Build React app
      run: npm run build
      env:
        CI: true

    # Component Testleri
    - name: Run Component Tests
      run: npx cypress run --component
      env:
        CI: true

    # Development sunucusunu başlat
    - name: Start development server
      run: |
        npm run start & npx wait-on http://localhost:3000
      env:
        CI: true

    # E2E Testleri
    - name: Run E2E Tests
      run: npx cypress run --e2e
      env:
        CI: true

    # Test sonuçlarını kaydet
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: |
          cypress-react-app/cypress/videos
          cypress-react-app/cypress/screenshots
          cypress-react-app/cypress/reports
        retention-days: 30

    # Hata durumunda screenshot'ları kaydet
    - name: Upload Failure Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress-react-app/cypress/screenshots
        retention-days: 5